### ISSUE TITLE
Metadata aggregated from subdataset not available in `meta-dump -r` output

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-metalad#131]
I'm having trouble accessing specific metadata aggregated from a subdataset when running `datalad meta-dump -r`

I'm working with the studyforrest dataset, which has many subdatasets including `original/3T_multiresolution_fmri`. I wanted to test the `metalad_studyminimeta` extractor and see how the extracted metadata can be propagated to the toplevel dataset. So I added a `.studyminimeta.yaml` file for the `original/3T_multiresolution_fmri` subdataset. Then I ran (from the root dataset):

```
datalad meta-extract -d original/3T_multiresolution_fmri metalad_studyminimeta > original/3T_multiresolution_fmri/metablob.json

datalad meta-add -d original/3T_multiresolution_fmri original/3T_multiresolution_fmri/metablob.json
```

These ran without any problems, and I could confirm with a `datalad meta-dump -d original/3T_multiresolution_fmri` that the studyminimeta-data was part of the subdataset metadata store.

Then I aggregated this to the toplevel, running the following from the root dataset:
```
datalad meta-aggregate -d . original/3T_multiresolution_fmri
```
which to my understanding should add the aggregated subdataset metadata to the toplevel metadata store. But when I finally run `datalad meta-dump -r` on the toplevel dataset, I cannot find any of the studyminimeta-data in the output.

Any thoughts as to what might be wrong here?

**Comment by christian-monch** [comment]
I could not recreate the behavior here with a simple test (using datalad-metalad master @26f0137c9931fdc59e0067cd3fec3125039646be). I find the aggregated dataset in the root dataset. The JSON-object that is emitted for the aggregated dataset has a "dataset-path"-key with a value that is not empty or ".", i.e. the value is the subdataset-path relative to the top-level directory.

**Comment by jsheunis** [comment]
Thanks @christian-monch. I haven't been able to build a reproducer, but will do that as soon as I get the chance to.

**Comment by christian-monch** [comment]
@jsheunis With pr #187 all all metadata should be dumped now. Some metadata was not displayed earlier, if it was not extracted from the same sub-dataset version, that is present in the root dataset in the version that was used when extracting.

Clearer:
Only metadata from some dataset version was displayed earlier by dump
Now all metadata is displayed on dump.
