### ISSUE TITLE
`meta-conduct` stalls after extracting, before adding, metadata

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-metalad#142]
_System: Mac
Python: 3.9.5
DataLad: 0.15.0
Metalad: most recent_

---
After running `meta-conduct` with the following command:

```
datalad meta-conduct datalad_metalad/pipelines/extract_metadata_pipeline.json \
    traverser:/Users/jsheunis/Documents/psyinf/Data/sfdata_21sep/studyforrest-data/original/3T_multiresolution_fmri \
    extractor:Dataset \
    extractor:metalad_core_dataset
```
and with a pipeline (`extract_metadata_pipeline.json`) having the following configuration:

```
{
  "provider": {
    "module": "datalad_metalad.provider.datasettraverse",
    "class": "DatasetTraverser",
    "name": "traverser",
    "arguments": [],
    "keyword_arguments": {}
  },
  "processors": [
    {
      "module": "datalad_metalad.processor.extract",
      "class": "MetadataExtractor",
      "name": "extractor",
      "arguments": [],
      "keyword_arguments": {}
    },
    {
      "module": "datalad_metalad.processor.add",
      "class": "MetadataAdder",
      "name": "adder",
      "arguments": [],
      "keyword_arguments": {}
    }
  ]
}
```

the execution just stalls after extracting the metadata. The extraction part looks like it works fine (see output below) but then nothing happens further, and the command prompt doesn't return to normal.

```
meta_conduct(ok): /Users/jsheunis/Documents/psyinf/Data/sfdata_21sep/studyforrest-data/original/3T_multiresolution_fmri/sub-06/func/sub-06_task-orientation_acq-r14_run-01_bold.json
.
.
.
meta_conduct(ok): /Users/jsheunis/Documents/psyinf/Data/sfdata_21sep/studyforrest-data/original/3T_multiresolution_fmri/sub-06/anat/sub-06_acq-r30_T1w.json
  [926 similar messages have been suppressed; disable with datalad.ui.suppress-similar-results=off]

```

I've ran the same command with a pipeline excluding the `adder` and then it doesn't stall, hence my thinking that the issue is the adder part. Is there a way to inspect what's happening at that point, while the output stalls? I've ran the command with the `--dbg` flag but this yields nothing new. I've also used a different extractor (`metalad_core` and `metalad_studyminimeta`) and this results in the same stalling behaviour. Supposedly if only one metadata object is to be added (e.g. resulting from `studyminimeta` extraction on the dataset level), then the adder shouldn't be taking **that** long?

On a related note, I see that `meta-conduct` outputs a json-line per tree item in the directory (dataset and files), even if the extractor is only on the dataset level. Is this expected behaviour? From a UX perspective, this is a bit confusing, since one would expect the output to relate directly to what one is extracting.

**Comment by christian-monch** [comment]
There might be a file-lock hanging around in `${dataset}/.datalad/locks/metadata-model-git.lock`, because it is currently not removed when an exception is raised.

Please try to remove the  lock-file if you are sure that no other process is writing metadata to the repository

**Comment by jsheunis** [comment]
Thanks this solved the issue.
