### ISSUE TITLE
Update Appveyor config to use new codecov uploader

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad-metalad#152]
On June 9, codecov released a new version of their coverage uploader program to replace the old bash uploader, which will stop working on February 1 and is currently experiencing scheduled brownouts; see [this blog post](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) for more information.  This repository's Appveyor config installs the codecov uploader [provided by Chocolatey](https://community.chocolatey.org/packages/codecov), which has not yet updated to the newer version.  If the Chocolatey package is not updated in time, the Appveyor config must be updated to install the new codecov uploader directly; see the linked blog post for instructions.

**Comment by christian-monch** [comment]
Thanks a lot for the issue. Using the new uploader now. Verification is still exiting with an error on windows-appveyor (which is not related to the verification itself)

**Comment by christian-monch** [comment]
New uploaded added, Windows integrity check still failing (see #189)
