### ISSUE TITLE
`meta_extract` should not yield error results for broken dataset specification

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#218]
It seems we have no design document on this yet, but the general pattern is to fail with exceptions when a command is called wrong. `meta_extract` requires a dataset, but when it cannot find one, it yields an error result. However, given that this is an immediately detectable error condition, error recovery is impossible, and quite likely an indication of an actual usage error (rather than an error that occurred during normal processing with adequate parameterization), I think this should change.

If this is not the case, the test implementation should acknowledge https://github.com/datalad/datalad/pull/6521 and be adjusted for `require_dataset()` always raising `NoDatasetFound`, such that no plain `ValueError` will bypass the `except` clause in `meta_extract`.

**Comment by christian-monch** [comment]
> It seems we have no design document on this yet, but the general pattern is to fail with exceptions when a command is called wrong. meta_extract requires a dataset, but when it cannot find one, it yields an error result. However, given that this is an immediately detectable error condition, error recovery is impossible, and quite likely an indication of an actual usage error (rather than an error that occurred during normal processing with adequate parameterization), I think this should change.

@mih: I like the pattern that you outlined, and I will apply it. In fact, previous versions of `meta_extract` raised NoDatasetFound-exceptions when a dataset could not be found at a given location (to be nitpicking: in this case, the command is not *called wrongly*, but the provided *parameter is not valid* for the intended processing). This behavior was changed after discussions with other team members. The argument was that there might be some short-term unavailability of a dataset that might prevent this execution of `meta-extract` from succeedings, but not subsequent executions. And an exception would be more likely to interrupt a long-running process and potentially lead to time-consuming re-calculations. I have not seen enough use cases to assert the validity of the given argument, therefore: yes, a design doc would be great! :-)
