### ISSUE TITLE
JSON output is an invalid input to jq after git clone

### ISSUE THREAD

**Issue by ddeepwel** [datalad/datalad-metalad#277]
Datalad metadata functions work fine, but when I pipe the output to jq, I receive the following error `parse error: Invalid numeric literal at line 1, column 15`. I receive this error on both mac osx 12.5 and on rocky linux 8.5.

Here's a sequence of reproducible steps:
```
datalad create -c text2git dicom-extract
cd dicom-extract
git clone https://github.com/ShahinSHH/COVID-CT-MD.git
datalad save -m "new data"
datalad meta-extract metalad_core | jq .
```

The `datalad meta-extract metalad_core` command runs fine without the pipe to jq. 

I can also confirm that this is somehow linked to the git cloning since I replaced that step with adding a dummy binary file and things worked fine.

**Comment by ddeepwel** [comment]
After reviewing I'm pretty sure this is because of the order of creating the datalad dataset and git clone.

Here I create a datalad dataset and then populate it with the git repo. Things run as expected if I run the git clone first followed by converting the repo into a dataset.

**Comment by christian-monch** [comment]
Releases version 0.4.3 of metalad. That should fix the problem.

**Comment by ddeepwel** [comment]
Looks to be working after the update!

**Comment by christian-monch** [comment]
> Looks to be working after the update!

Good to hear. Closing this issue
