### ISSUE TITLE
Document writing custom extractors

### ISSUE THREAD

**Issue by mslw** [datalad/datalad-metalad#281]
I'd like to propose a documentation article on writing custom extractors.

### Why documentation, and what would that cover?
As of now, the only resource for writing custom extractors are the example extractors (`metalad_example_dataset` and `metalad_example_file`) [included with metalad's source code](https://github.com/datalad/datalad-metalad/tree/master/datalad_metalad/extractors). This alone is very useful and sufficient to write a functional extractor. However, when writing my own, I had some doubts, and found that answers were scattered or required experimentation. I think a documentation article might explain, e.g.:

- what is the purpose of the `get_required_content` function, what could it do, and when it is called during extraction
- what does `get_version` represent, are there versioning conventions?
- are there any requirements for UUID?
- which fields in `ExtractorResult` are required, and how to format added metadata
- how to make the extractor discoverable to `meta-extract`

### Room for discussion
I believe that some of these things aren't set in stone yet, and the documentation page could be space for discussion as well. For example, I'm aware of these remarks in a DataLad-Neuroimaging PR:
- [regarding UUIDs](https://github.com/datalad/datalad-neuroimaging/pull/104#discussion_r811873896), a plain, random, UUIDv4 seems to be recommended, but there's also a suggestion of using non-random UUIDv5, which can encode namespace
- [regarding versions](https://github.com/datalad/datalad-neuroimaging/pull/104#discussion_r811896878), there was an expression of concern regarding when they would change; might be worth giving some recommendations, making some constraints, or emphasizing creator's freedom

### Who/when?
I can, most likely, write a draft tomorrow (hence I'm assigning myself), then I'll need to drop it for a while. Let me know if you have objections to the usefulness of such a document.

**Comment by adswa** [comment]
This was done in https://github.com/datalad/datalad-metalad/pull/282 and GitHub did not close this automatically.
