### ISSUE TITLE
files not shipped with/for tests in released version (or just needs are release?)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-metalad#288]
downstream testing against extensions in datalad core due to missing test files in a release, see e.g. in https://github.com/datalad/datalad/actions/runs/3112925414/jobs/5046909709 . But since passes in https://github.com/datalad/datalad-extensions/ , I guess it was fixed in `master` and might just need a release. Please do so, so we could have datalad core CI green again

**Comment by christian-monch** [comment]
Fixed by #290 , closing the issue
