### ISSUE TITLE
MNT: refactor `extract.py` to deduplicate code

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-metalad#366]
> Relatedly, I see in `extract.py` module that there is some code duplication, specifically (but not exclusively) in `perform_dataset_metadata_extraction` and `perform_file_metadata_extraction`, and especially if we now also add the handling of `get_required_content` for the file-level. Would it be useful to abstract some of this functionality out, or are there reasons for keeping the duplicated methods/code separate for dataset and file?

_Originally posted by @jsheunis in https://github.com/datalad/datalad-metalad/issues/287#issuecomment-1460073583_

**Comment by jsheunis** [comment]
Current plan:
- merge `do_file_extraction()` and `do_dataset_extraction()` into a single function `do__extraction()`, with a new argument `extractor_type`, which would be either `file` or `dataset`.
- merge `perform_file_metadata_extraction()` and `perform_dataset_metadata_extraction()` into a single function `perform_metadata_extraction`
- update tests accordingly

**Comment by christian-monch** [comment]
Fixed by PR #367
