### ISSUE TITLE
At version 0.4.18, failure to load interfaces to `datalad.api`

### ISSUE THREAD

**Issue by candleindark** [datalad/datalad-metalad#403]
At version 0.4.18, the interfaces of metalad failed to be loaded to `datalad.api` as depicted in the following.

```
Python 3.9.16 (main, Jan 20 2023, 12:37:03)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datalad.api import dl
[ERROR  ] Internal error, cannot import interface 'datalad_metalad.extract': ModuleNotFoundError(No module named 'importlib_resources')
[ERROR  ] Skipping unusable command interface 'datalad_metalad.extract.Extract' from extension 'metalad'
[ERROR  ] Internal error, cannot import interface 'datalad_metalad.aggregate': ModuleNotFoundError(No module named 'importlib_resources')
[ERROR  ] Skipping unusable command interface 'datalad_metalad.aggregate.Aggregate' from extension 'metalad'
[ERROR  ] Internal error, cannot import interface 'datalad_metalad.add': ModuleNotFoundError(No module named 'importlib_resources')
[ERROR  ] Skipping unusable command interface 'datalad_metalad.add.Add' from extension 'metalad'
[ERROR  ] Internal error, cannot import interface 'datalad_metalad.conduct': ModuleNotFoundError(No module named 'importlib_resources')
[ERROR  ] Skipping unusable command interface 'datalad_metalad.conduct.Conduct' from extension 'metalad'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'dl' from 'datalad.api' (/Users/isaac/.pyenv/versions/datalad-registry/lib/python3.9/site-packages/datalad/api.py)
```

**Comment by adswa** [comment]
Same problem in https://github.com/datalad/datalad-catalog/pull/394#issuecomment-1760398342

**Comment by christian-monch** [comment]
Should be fixed by `datalad-metalad` version `0.14.20`

**Comment by christian-monch** [comment]
@candleindark , sorry for the late answer. There were some issues with python <= 3.9 on Windows. They should be fixed by release `0.14.20` of `datalad-metalad`.

I am not sure that the error above is related to those issues though, is `dl` supposed to exist in `datalad.api`?

**Comment by candleindark** [comment]
@christian-monch My bad. It was not supposed to be `from datalad.api import dl`. It should have been `import datalad.api as dl`. At `0.4.18` `datalad-metalad`, `import datalad.api as dl` produces the following errors.

```
import datalad.api as dl
[ERROR] Internal error, cannot import interface 'datalad_metalad.extract': ModuleNotFoundError(No module named 'importlib_resources') 
[ERROR] Skipping unusable command interface 'datalad_metalad.extract.Extract' from extension 'metalad' 
[ERROR] Internal error, cannot import interface 'datalad_metalad.aggregate': ModuleNotFoundError(No module named 'importlib_resources') 
[ERROR] Skipping unusable command interface 'datalad_metalad.aggregate.Aggregate' from extension 'metalad' 
[ERROR] Internal error, cannot import interface 'datalad_metalad.add': ModuleNotFoundError(No module named 'importlib_resources') 
[ERROR] Skipping unusable command interface 'datalad_metalad.add.Add' from extension 'metalad' 
[ERROR] Internal error, cannot import interface 'datalad_metalad.conduct': ModuleNotFoundError(No module named 'importlib_resources') 
[ERROR] Skipping unusable command interface 'datalad_metalad.conduct.Conduct' from extension 'metalad' 
```

All tests for Datalad-Registry passed with `datalad-metalad` `0.14.20`. Thanks.

By the way, why version `0.14.20` and not version `0.4.20`? Was it a typo?

**Comment by christian-monch** [comment]
> @christian-monch My bad. It was not supposed to be `from datalad.api import dl`. It should have been `import datalad.api as dl`. At `0.4.18` `datalad-metalad`, `import datalad.api as dl` produces the following errors.
> 
> ```
> import datalad.api as dl
> [ERROR] Internal error, cannot import interface 'datalad_metalad.extract': ModuleNotFoundError(No module named 'importlib_resources') 
> [ERROR] Skipping unusable command interface 'datalad_metalad.extract.Extract' from extension 'metalad' 
> [ERROR] Internal error, cannot import interface 'datalad_metalad.aggregate': ModuleNotFoundError(No module named 'importlib_resources') 
> [ERROR] Skipping unusable command interface 'datalad_metalad.aggregate.Aggregate' from extension 'metalad' 
> [ERROR] Internal error, cannot import interface 'datalad_metalad.add': ModuleNotFoundError(No module named 'importlib_resources') 
> [ERROR] Skipping unusable command interface 'datalad_metalad.add.Add' from extension 'metalad' 
> [ERROR] Internal error, cannot import interface 'datalad_metalad.conduct': ModuleNotFoundError(No module named 'importlib_resources') 
> [ERROR] Skipping unusable command interface 'datalad_metalad.conduct.Conduct' from extension 'metalad' 
> ```
> 
> All tests for Datalad-Registry passed with `datalad-metalad` `0.14.20`. Thanks.
> 
> By the way, why version `0.14.20` and not version `0.4.20`? Was it a typo?

I F***, yes it was.

**Comment by candleindark** [comment]
@christian-monch Are you going to modify the version, or are you going to keep the `0.14.20`? If you are not going to change the `0.14.20` version, I will just point Datalad-Registry to it.

**Comment by christian-monch** [comment]
> @christian-monch Are you going to modify the version, or are you going to keep the `0.14.20`? If you are not going to change the `0.14.20` version, I will just point Datalad-Registry to it.

I modified it, i.e. deleted `0.14.20`. Please don't point the registry to it. The correct version is `0.4.20`. Sorry for the incvonenience

**Comment by candleindark** [comment]
> > @christian-monch Are you going to modify the version, or are you going to keep the `0.14.20`? If you are not going to change the `0.14.20` version, I will just point Datalad-Registry to it.
> 
> @candleindark I modified it, i.e. deleted `0.14.20`. Please don't point the registry to it. The correct version is `0.4.20`. Sorry for the incvonenience

Thanks a lot for the update and no inconvenience at all.
