### ISSUE TITLE
Some tests errorring out while testing datalad-extensions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-metalad#405]
Might be another reincarnation of #403 but datalad-extensions testing has been failing for a while with a summary like

```
=========================== short test summary info ============================
FAILED extractors/legacy/tests/test_audio.py::test_audio - ValueError: unknown extractor class: AudioMetadataExtractor
FAILED extractors/legacy/tests/test_exif.py::test_exif - ValueError: unknown extractor class: ExifMetadataExtractor
FAILED extractors/legacy/tests/test_frictionless_datapackage.py::test_get_metadata - ValueError: unknown extractor class: type
FAILED extractors/legacy/tests/test_image.py::test_image - ValueError: unknown extractor class: ImageMetadataExtractor
FAILED tests/test_extract.py::test_legacy2_dataset_extraction_result - ValueError: unknown extractor class: type
FAILED tests/test_extract.py::test_legacy2_file_extraction_result - ValueError: unknown extractor class: DataladCoreMetadataExtractor
```

FWIW -- this seems to be the only extension which had such unfortunate fails

**Comment by yarikoptic** [comment]
ping @christian-monch and @mih -- fails continue. Would be nice to get them addressed to avoid "failing CI fatigue"

**Comment by christian-monch** [comment]
> ping @christian-monch and @mih -- fails continue. Would be nice to get them addressed to avoid "failing CI fatigue"

@yarikoptic , sorry for the delayed answer.  Release `0.14.20` of `datalad-metalad` should fix the problem with extractor-gathering that was introduced in `0.14.18`. I am not sure where the log-excerpt above stems from, but I checked a number of `datalad-extensions` tests and they seem to come up green.

If the problem persists, could you point me to the build?

**Comment by yarikoptic** [comment]
it is all green now -- great, thanks! Let's consider addressed
