### ISSUE TITLE
Metadata for backup archive

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#46]
@christian-monch Here is a concrete project to jump-start work on this extension. @adswa this is something that might also be a relevant use case for the handbook.

Status quo:

We have tons of archived projects in 7z files. There are largely inaccessible: huge, no comprehensible or uniform structure. They are essentially dead weight that is only kept around, because "we must not loose data".

Idea:

- create a DataLad dataset for each 7z/project that indexes its content via (`add-archive-content`)
- put all dataset in a store on a store node (`bulk1`)
- additionally put all 7z files (or rather their annex keys) on an archive solution (JSC `ARCHIVE`)
- aggregate very basic metadata into a superdataset `(inm7)-archive`
- provide a checkout of just that superdataset on the cluster (`juseless`)

This would make archives projects much more accessible:

- what do we have?
- how much is it?
- who made it?
- does it have relevant data?

**Comment by christian-monch** [comment]
Solved with the `studyminimeta` schema and its accompanying indexers
