### ISSUE TITLE
Cut a release to unblock datalad RM RF?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-metalad#66]
ref: https://github.com/datalad/datalad/pull/5441

although not certain about the state since both build icons are grey in README, although testing of released version seems to be green in https://github.com/datalad/datalad-extensions/

**Comment by yarikoptic** [comment]
is there any roadmap to see a release of metalad in the future to unblock a minor deprecation RM https://github.com/datalad/datalad/pull/5441 ?

**Comment by christian-monch** [comment]
Addressed in https://github.com/datalad/datalad/pull/6060

Datalad's metalad extension tests are green again

**Comment by christian-monch** [comment]
@yarikoptic, @mih: we could do a 1.0.0a1 release. I know that we do not use major version numbers larger than zero usually, but since metalad has changed a bit and is incompatible (cmdline as well as metadata storage format and location) with the old version, and I don't want to break any existing applications, I would go for `1.0.0a1`. It sticks out from our unix-style versioning scheme though.

Any thoughts?

**Comment by mih** [comment]
No version has provided complete functionality so far. Key maintenance features were never implemented. Any release was essentially a dev snapshot. From my POV I'd continue with that practice and not change schemes. But ultimately, I dont care too much.

That being said, two things:

1) we tend to use "rcX" for release candidates

2) I dont understand how a 1.0 release breaks other code less than a 0.50 release?

**Comment by christian-monch** [comment]
> I dont understand how a 1.0 release breaks other code less than a 0.50 release?

Technically there is no difference. But our versioning scheme looks like "semantic versions" and an identical major version would indicate compatibility. But that is probably irrelevant,

Will go with `0.3.0rc1`

**Comment by christian-monch** [comment]
@yarikoptic Released. Sorry for the long wait.

**Comment by yarikoptic** [comment]
release was made, thanks @christian-monch !
