### ISSUE TITLE
meta-dump warning with confusion potential

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#76]
I explored under the assumption that `meta-dump` is a command that I would use to get metadata that is stored in a dataset on some content.

```
% datalad meta-dump
[WARNING] No git-mapped datalad metadata model found in: . 
```

Thoughts that came to my mind when I experienced this:

- does "no model found" mean there is no metadata, or is there a technical problem (it warns me) that some model is missing, hence it cannot report
- is it possible to switch to something that is not "git-mapped" and that would then report metadata?
- if there is no metadata, why does it warn me? I did not ask for anything specific. How would I be able to not be warned and answer the question "is there metadata?"

**Comment by christian-monch** [comment]
Fixed in PR #112
