### ISSUE TITLE
Keyword initialization coding style

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#77]
Just an observation I made when going through the code:

```py
        extraction_parameters = ExtractionParameter(
            realm,
            source_dataset,
            UUID(source_dataset.id),
            extractor_class,
            extractorname,
            args_to_dict(extractorargs),
            dataset_tree_path,
            file_tree_path,
            root_primary_data_version,
            source_primary_data_version,
            source_dataset.config.get("user.name"),
            source_dataset.config.get("user.email"))
```

I find this style hard to read, and eventually expensive and error-prone in maintenance. I am not too familiar with `dataclass`, but I think it is possible to use keyword-style ala `source_dataset_id=UUID(source_dataset.id)`. IMHO this makes it much easier to spot/grep issues when a larger RF is happening.

```
       extraction_parameters = ExtractionParameter(
            realm,
            source_dataset,

```

**Comment by christian-monch** [comment]
Yes, keyword args are supported in dataclasses. Good point. Will be addressed in PR
