### ISSUE TITLE
Concept of meta-extract -d vs -i options

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#78]
The new `meta-extract`, unlike the old one, is not a read-only operation. Without `-i` it will modify the dataset that metadata is extracted from (by storing the extract in its repository). I would argue that this default behavior is not a good default.

Having metadata is much more relevant when not having the data around. I would suspect that my personal use case -- of extracting metadata from a dataset A into a different dataset B, because A will not be (as) easily accessible as A -- is a better standard. Another standard case is the extraction of custom metadata from a 3rd-party subdataset. Modifying the source (as it would be the default now), will require hosting a repository copy (at minimum) -- that is rarely desirable.

I will file a related issue in a second (on the reporting capabilities of `meta-extract`), but another question is: why use `--into` instead of `--dataset` to identify the target dataset? A file is identified by path. Why not a dataset? What about directories?

`--dataset` is generally the "what dataset to operate on" argument. I kinda makes sense to me to use it for `--into` and do the rest by path argument(s).

**Comment by christian-monch** [comment]
`meta-extract` does now only extract metadata via extractors. Adding is done by `meta-add`
