### ISSUE TITLE
Ability to perform read-only metadata extraction

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#79]
It does not seem possibly to use `meta-extract` for plain reporting (without storage of the extract). This blurs the conceptual line between `meta-extract` and `meta-aggregate`. At present `meta-extract` does some kind of "aggregation" in a (different) dataset identified by `--into`.

Being able to generate metadata without intermediate storage seems like a worthwhile usecase to me. If would make it possible to work with metadata of present primary dataset (at the curation site) without putting strain on the repository object store, and is likely faster when working with changing data -- that may not even be in a dataset ((saved) yet).

**Comment by christian-monch** [comment]
Fixed in PR #99
