### ISSUE TITLE
meta-extract logging behavior

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#81]
This is what I get from processing a single file
```
% datalad meta-extract metalad_core_file mike
[INFO   ] performing file level extracting for file at /tmp/mike/mike 
[INFO   ] added file metadata result to realm AnnexRepo('/tmp/mike'), dataset tree path MetadataPath(''), file tree path MetadataPath('mike') 
Core file metadata extraction: 0.00File [00:00, ?File/s]%                                                                  
```

The first INFO message should be a progress report. It seems there is already a progress bar running (but not used, see trailing `0.00File [00:00, ?File/s]`).

The second INFO log looks like it should not be there, but this information should become a property of the result record (see #80).

**Comment by christian-monch** [comment]
Logging level has been raised to DEBUG. progressbar remainders removed
