### ISSUE TITLE
meta-dump: `*:*` DATASET_FILE_PATH_PATTERN not working

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#83]
The documentation suggested that something like the following would work:

```
% datalad meta-dump \*:\*
[ERROR  ] could not locate metadata for dataset path * in tree version None in realm git:. 
% datalad meta-dump '*:*'
[ERROR  ] could not locate metadata for dataset path * in tree version None in realm git:. 
```

In case this is a misspecification, I would have expected an exception, or a error result. However, in both cases I get an ERROR log message only, and the command exists with success.

What does work is:

```
% datalad meta-dump '.:*'
```

but this is not obvious, because the default result renderer does not handle it (missing `path` property maybe?). This makes it talk, though:

```
% datalad -f json_pp meta-dump '.:*'
```

**Comment by christian-monch** [comment]
This is fixed by #106
