### ISSUE TITLE
Default behavior of `meta-aggregate` surprising

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#88]
Given:

> As a result of the aggregation, the metadata of all specified sub-datasets will be available in the root metadata realm.

I did not expect a plain

```
% datalad meta-aggregate
meta_aggregate(ok): [aggregation performed]
```

to work. It is not clear to me what it did. The result record has not additional info:

```
{
  "action": "meta_aggregate",
  "backend": "git",
  "realm": ".",
  "status": "ok"
}
```

Maybe a dedicated example in the docs can illustrate this use case, if it is a valid one.

**Comment by christian-monch** [comment]
That command does not actually perform any aggregation. It should say "nothing to aggregate" or "nothing to aggregate, please provide ...". Will be fixed

**Comment by bpoldrack** [comment]
@christian-monch : `status='impossible'`, I think or even `InsufficientArgumentsError`.

**Comment by christian-monch** [comment]
Result structure with "error" is used to report that no valid metadata stores were found to aggregate
