### ISSUE TITLE
meta-extract with --format jsonld fails sometimes

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-metalad#9]
I observed a few crashes while playing around with ``meta_extract`` in [this dataset](https://github.com/adswa/multimatch_forrest) and trying to use ``--format jsonld`` .

A meta-extraction using ``metalad_core`` to ``--format jsonld`` failed with an AttributeError after metadata extraction
```sh
[INFO] Extracted core metadata from /home/adina/repos/multimatch_forrest 
[INFO] Finished core metadata extraction from <Dataset path=/home/adina/repos/multimatch_forrest> 
[INFO] Finished metadata extraction from <Dataset path=/home/adina/repos/multimatch_forrest> 
[ERROR] 'list' object has no attribute 'keys' [extract.py:custom_result_renderer:428] (AttributeError)
```
It happens when I don't specify ``-f``, but it does *not* happen if I specify formatting to pretty-printed JSON with ``-f json_pp``.
That is, this command works fine:
```sh
datalad -f json_pp meta-extract -d . --source metalad_runprov --source metalad_core --format jsonld
```

While this command produces the above Error:
```sh
datalad meta-extract -d . --source metalad_runprov --source metalad_core --format jsonld
```

Furthermore, these commands (not using ``metalad_core`` anymore, but also formatting to ``jsonld``, with or without pretty-printed JSON) 
```sh
datalad meta-extract -d . --source metalad_runprov --format jsonld
```

```sh
datalad -f json_pp meta-extract -d . --source metalad_runprov --format jsonld
```

also throw an error:
```sh
[ERROR  ] 'metalad_core' [__init__.py:collect_jsonld_metadata:239] (KeyError) 
```

but without ``--format jsonld`` it works fine:

```sh
datalad -f json_pp meta-extract -d . --source metalad_runprov 
```

**Comment by mih** [comment]
Thanks for the report. Except for the last issue all this should work with #16 now. I cannot replicate the last issue at all, and cannot see how it would happen. Please recheck with this PR in place, maybe it could fixed in the meantime.

**Comment by adswa** [comment]
```
datalad meta-extract -d . --source metalad_runprov --source metalad_core --format jsonld
```

works now, indeed! 
But for 

```
datalad meta-extract -d . --source metalad_runprov --format jsonld
```
and
```
datalad -f json_pp meta-extract -d . --source metalad_runprov --format jsonld
```

I am still running into this cryptic KeyError. I'm playing around with it and will let you know if I think of something insightful.

**Comment by mih** [comment]
Let me know which dataset it happens with.

**Comment by adswa** [comment]
Its still this one: https://github.com/adswa/multimatch_forrest

**Comment by mih** [comment]
Ah, yes. Thx, will check...

**Comment by adswa** [comment]
Not sure whether its really helpful (especially since you can't reproduce the problem -- might be something in my setup), but I'll document a short ``pbd`` detour. I can at least tell you what is failing how, and maybe you can then tell me whether that is my systems/calls/repos/... fault ;-)

The error occurs in [l250](https://github.com/datalad/datalad-metalad/blob/524d7c6bc6f0f370128c38e1ae81241f9b1eb59a/datalad_metalad/__init__.py#L250) of ``__init_.py``

```sh
╰─➤ datalad -f json_pp meta-extract -d . --source metalad_runprov --format jsonld

[ERROR  ] 'metalad_core' [__init__.py:collect_jsonld_metadata:250] (KeyError)
```

so I'm ``pdb``'ing at the top of the function:
```python
    import pdb; pdb.set_trace()
    if res['type'] == 'dataset':
        _native_metadata_to_graph_nodes(
            res['metadata'],
            nodes_by_context,
            contexts,
        )
    else:
        fmeta = res['metadata']
        fid = fmeta['metalad_core']['@id']
        _native_metadata_to_graph_nodes(
```

That enters the debugger quite immediately. At first, ``res['type'] == 'dataset'`` actually evaluates to ``True``:

<details>
<summary> See contents of resitems() </summary>

```
(Pdb) res.items()
dict_items([('path', '/home/adina/repos/multimatch_forrest'), ('type', 'dataset'), ('status', 'ok'), ('metadata', {'metalad_runprov': {'@context': 'http://openprovenance.org/prov.jsonld', '@graph': [{'@id': '960c637eb4a92d5245b4272d52959e280b10f4f1', '@type': 'activity', 'atTime': '2019-05-12T19:39:05+02:00', 'prov:wasAssociatedWith': {'@id': 'Adina_Wagner<adina.wagner@t-online.de>'}, 'rdfs:comment': '[DATALAD RUNCMD] compute average scanpath similarity per scanpath'}, {'@id': 'c44626ba6b06f01bd990901d8d5399ac300fb126', '@type': 'activity', 'atTime': '2019-01-10T17:53:18+01:00', 'prov:wasAssociatedWith': {'@id': 'Adina_Wagner<adina.wagner@t-online.de>'}, 'rdfs:comment': "[DATALAD RUNCMD] code/compute_allruns.py -p 'output/run*/..."}, {'@id': 'cae1b53db0a3036386a316dce804efe237450504', '@type': 'activity', 'atTime': '2019-05-06T14:07:59+02:00', 'prov:wasAssociatedWith': {'@id': 'Adina_Wagner<adina.wagner@t-online.de>'}, 'rdfs:comment': '[DATALAD RUNCMD] chunk 15min eye movement data into REMoDNaV scanpaths'}, {'@id': 'ce648eaabdc72a30c5158ed5ac532a211f998637', '@type': 'activity', 'atTime': '2019-05-10T19:05:48+02:00', 'prov:wasAssociatedWith': {'@id': 'Adina_Wagner<adina.wagner@t-online.de>'}, 'rdfs:comment': '[DATALAD RUNCMD] compare all the scanpaths'}, {'@id': 'Adina_Wagner<adina.wagner@t-online.de>', '@type': 'agent', 'name': 'Adina Wagner', 'email': 'adina.wagner@t-online.de'}]}})])

```

</details>

We then progress further into ``_native_metadata_to_graph_nodes`` which gets us into ``extract.py`` [l369](https://github.com/datalad/datalad-metalad/blob/524d7c6bc6f0f370128c38e1ae81241f9b1eb59a/datalad_metalad/extract.py#L369). There is this for-loop that seems to run through all contents of the dataset (?) ([for res in _proc](https://github.com/datalad/datalad-metalad/blob/524d7c6bc6f0f370128c38e1ae81241f9b1eb59a/datalad_metalad/extract.py#L362) ) and then seems to propagate the first entry of _proc forward -- 
``format`` is 'jsonld', hence with that single entry as ``res`` we get back into ``collect_jsonld_metadata()`` in l375.

This is what ``res`` is now:
```
(Pdb) p res
{'path': '/home/adina/repos/multimatch_forrest/allruns.tsv', 'type': 'file', 'status': 'ok', 'metadata': {'metalad_runprov': {'@id': 'datalad:SHA1-s50776--5c1e2f86b3913b15bad834f99e83e65cb14fff25', '@type': 'entity', 'prov:wasGeneratedBy': {'@id': '960c637eb4a92d5245b4272d52959e280b10f4f1'}}}, 'parentds': '/home/adina/repos/multimatch_forrest'}
```

and this lacks the ``metalad_core`` key where l250 (``fid = fmeta['metalad_core']['@id']``) is failing.

Does that make sense?

**Comment by mih** [comment]
Ok, found it. It is triggered by the manual non-specification of `metalad_core` as an extractor (which is on by default, if nothing is selected). Hence,

`datalad -f json_pp meta-extract -d . --source metalad_runprov --source metalad_core --format jsonld`

works as desired.

I will push a fix that protects against this fairly in the above scenario shortly.

**Comment by adswa** [comment]
Cool, thx!
