### ISSUE TITLE
Metadata store parameter [Nomenclature]

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-metalad#97]
Different meta-... commands use different names for the metadata store-parameter. We must:

1. Settle on a name
2. Use this name in all meta-... commands
3. Use this name in all documents

A proposal would be:

- _metadata model instance_: an instance of the metadata model, i.e. a set of metadata that can be accessed through the ADTs defined in the module `dataladmetadatamodel`.
 
- _metadata-store_: the object that stores a metadata model instance. It is associated with a _metadata-store address_, that identifies it. The metadata-store object and metadata-store address are depending on the storage backend that is used for the metadata model instance. For example, with a git-backend, the metadata-store object would be a local git-repository and the metadata-store address would be a path the the git-repository.

**Comment by christian-monch** [comment]
metadata-store used in commands as of 8bd23fd4661ed569f4f6c8dd66e1fedc1032e47b

**Comment by mih** [comment]
I just read through the docstring of `meta-add`, and I have mixed feelings re "metadata model instance". Reading it my brain seems to initially discard the entire construct as "maybe understand later". When I do try to understand the choice of name, it makes sense, but still feels overly sophisticated -- although that may still be a side-effect of a concept mismatch that I have (see #90).

I am not sure if the proposal above is "metadata model instance" vs. "metadata-store", but if it is the latter seems way more intuitive.

**Comment by christian-monch** [comment]
"Metadata model instance" and "metadata-store" are almost identical. The store is the container and the metadata model instance is what is stored in it, i.e. a container in a specific state.

I propose the use of "metadata-store" instead of "realm", and to use "metadata" when we refer to the data stored in the metadata-store (this "metadata" is an instance of the metadata model, but that is unnecessarily detailed).

**Comment by bpoldrack** [comment]
I'm not sure it's useful to talk about either one. This is a datalad command. I'm a user. The only thing I can and want to store metadata in, is the dataset. From that perspective: What's the difference between the repository and a metadata store? Immediatly raises questions. What is it? Do I need something in addition to what I already have? Where would I get a store from? Why do I need to know that?

To me that parameter should simply be `--dataset` and be talked about in that way.

**Comment by christian-monch** [comment]
As a result of the discussion in the Metalad group, the distinction between dataset and metadata store for the dataset should not be presented to the user. This issue is therefore moved to issue #119
